language: c

addons:
 apt:
  packages:
   -cmake
   
before_install: git clone https://github.com/libgit2/libgit2.git

install:
- cd libgit2
- mkdir build && cd build
- cmake ..
- cmake --build .

script:
- cd ..
- cd ..
- cd ..
- ls -l
- gcc -I./libgit2/include main.c -L./libgit2/build -lgit2 -o main
