language: c

notifications:
 email: false

install:
- cd libgit2
- mkdir build && cd build
- cmake -DBUILD_CLAR=OFF ..
- cmake --build .

script:
- cd ..
- cd ..
- cd scripts
- chmod +x linux_build.sh
- ./linux_build.sh
