language: c
   
before_install: git clone https://github.com/libgit2/libgit2.git

install:
- cd libgit2
- mkdir build && cd build
- cmake -DBUILD_CLAR=OFF ..
- cmake --build .

script:
- cd ..
- cd ..
- gcc -I./libgit2/include main.c -L./libgit2/build -lgit2 -o main
